modLoader = 'lowcodefml'
loaderVersion = '[1,)'
license = 'Apache-2.0'
showAsResourcePack = false
issueTrackerURL = 'https://github.com/suerion/hardcore-revive-plus/issues'

mods = [
	{
		modId = 'mr_hardcore_reviveplus',
		version = '${version}',
		displayName = 'Hardcore Revive+',
		description = 'A highly configurable data pack that lets you revive your friends in Hardcore mode.',
		logoFile = 'hardcore-revive-plus_pack.png',
		authors = 'StapleTT, Suerion',
		displayURL = 'https://modrinth.com/project/Huz7HM6Q'
	}
]